Removed deprecated API method and code warning, updated to Swift 5
zhxnlai/ZLSwipeableViewSwift pull request #141
Opened 2019-10-09 21:47 UTC by domeniconicoli

-Removed deprecated API method
-Updated to Swift 5 version
-Removed many code warnings

2019-10-12 05:29 UTC, AndrewSB requested changes
this is super helpful, thanks for taking the time. we can bump the version after this PR is merged. take a look at my notes and I’m happy to merge after you’ve made the changes I requested

2019-10-12 05:29 UTC, AndrewSB commented on ZLSwipeableViewSwiftDemo/ZLSwipeableViewSwiftDemo.xcodeproj/project.pbxproj
> +						DevelopmentTeam = 89D52653SY;
could you remove this change?

2019-10-12 05:29 UTC, AndrewSB commented on ZLSwipeableViewSwiftDemo/ZLSwipeableViewSwiftDemo.xcodeproj/project.pbxproj
> +						DevelopmentTeam = 89D52653SY;
this one too

2019-10-12 05:29 UTC, AndrewSB commented on ZLSwipeableViewSwiftDemo/ZLSwipeableViewSwiftDemo.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 89D52653SY;
ditto, delete please

2019-10-12 05:29 UTC, AndrewSB commented on ZLSwipeableViewSwiftDemo/ZLSwipeableViewSwiftDemo.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 89D52653SY;
all of the ones that add your development team, there are a couple more in the file

2019-10-12 05:29 UTC, AndrewSB commented on ZLSwipeableViewSwiftDemo/ZLSwipeableViewSwiftDemo.xcodeproj/project.pbxproj
> +				ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;
is this required?

2019-10-12 08:37 UTC, domeniconicoli commented
Hi Andrew,
I made the requested changes.
Let me know if everything is fine now.

Best Regards.

2019-10-13 12:39 UTC, merged

2019-10-13 12:57 UTC, AndrewSB commented
pushed a new release: https://github.com/zhxnlai/ZLSwipeableViewSwift/releases/tag/0.0.9